package co.com.sebuscan.missing.people.csv

class CsvFile(CodDesaparecido:String,
              NombresDesaparecido:String,
              ApellidosDesaparecido:String,
              NombresBusqueda:String,
              Sexo:String,
              CodMunicipio:String,
              NombreMunicipio:String,
              CodDepartamento:String,
              NombreDepartamento:String,
              CodPais:String,
              NombrePais:String,
              CodigoAbreviado:String,
              Bandera:String,
              LocalBandera:String,
              FechaNacimiento:String,
              FechaDesaparicion:String,
              EdadDesaparicion:String,
              IdEstadoDesaparecido:String,
              DescripcionEstadoDesaparecido:String,
              IdTipoDesaparecido:String,
              DescripcionTipoDesaparecido:String,
              IdFuenteDesaparecido:String,
              DescripcionFuenteDesaparecido:String,
              SenalesParticulares:String,
              Estatura:String,
              IdContextura:String,
              DescripcionContextura:String,
              IdRaza:String,
              DescripcionRaza:String,
              IdEstratoSocioeconomico:String,
              DescripcionEstratoSocioeconomico:String,
              Ranking:String,
              DescripcionDesaparecido:String,
              FechaRegistro:String,
              FechaAparicion:String,
              ListaYoutube:String,
              CodUsuario:String,
              UID:String,
              CorreoUsuario:String,) {
}